- id: chmod
  name: change file permissions
  entry: one-liners chmod
  types: [file]
  files: ^$
  language: python

- id: regex
  name: regular expression search and replace
  entry: one-liners regex
  types: [file]
  files: ^$
  language: python
